### ISSUE TITLE
Unable to use esc in a normal way after calibration

### ISSUE THREAD

**Issue by raghu5910** [lobodol/ESC-calibration#1]
Hi,

After using this script for calibration, I was unable to use ESC in a normal way. The only way that I could spin the motor was by using same script again. I think it keeps being in programming mode after calibration. Is there any script that can be used to unset it.

**Comment by lobodol** [comment]
Hi, what is the reference of your ESC?
I suggest you to get the documentation of your ESC to see if there is some particular information, such as frequency or pulse durations.

**Comment by raghu5910** [comment]
Thanks. I got a solution from DYS documentation. I just need to initialize with lowest throttle (1000 microseconds) to start in a normal way.
